export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_GROUPS = 'GET_PRODUCT_GROUPS';
export const GET_FILTERED_PRODUCTS = 'GET_FILTERED_PRODUCTS';
export const GET_SHELFS = 'GET_SHELFS';
